services:
  user-service:
    platform: linux/amd64
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ..
      dockerfile: implementation-go/user-service/Dockerfile
    container_name: go-user-service
    ports:
      - "50051:50051"

  ledger-service:
    platform: linux/amd64
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ..
      dockerfile: implementation-go/ledger-service/Dockerfile
    container_name: go-ledger-service
    ports:
      - "50052:50052"

  wallet-service:
    platform: linux/amd64
    mem_limit: 512m
    cpus: 0.5
    build:
      context: ..
      dockerfile: implementation-go/wallet-service/Dockerfile
    container_name: go-wallet-service
    ports:
      - "50053:50053"
    environment:
      - USER_SERVICE_ADDR=user-service:50051
      - LEDGER_SERVICE_ADDR=ledger-service:50052
    depends_on:
      - user-service
      - ledger-service